# Generated by Django 5.2 on 2025-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
