# Generated by Django 5.2 on 2025-06-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clase_css', models.CharField(max_length=100)),
                ('libreria', models.CharField(choices=[('bootstrap', 'Bootstrap Icons'), ('fontawesome', 'Font Awesome'), ('otros', 'Otro')], max_length=50)),
            ],
        ),
    ]
