# Generated by Django 5.1.5 on 2025-06-12 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconos', '0002_icono_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='icono',
            name='libreria',
            field=models.CharField(choices=[('fa', 'Font Awesome'), ('bs', 'Bootstrap Icons')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='icono',
            unique_together={('usuario', 'clase_css', 'libreria')},
        ),
        migrations.CreateModel(
            name='IconoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconos.icono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'icono')},
            },
        ),
    ]
