# Generated by Django 5.1.5 on 2025-06-12 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconos', '0003_alter_icono_libreria_alter_icono_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='icono',
            unique_together={('usuario', 'clase_css')},
        ),
        migrations.AlterField(
            model_name='icono',
            name='libreria',
            field=models.CharField(choices=[('bootstrap', 'Bootstrap Icons'), ('fontawesome', 'Font Awesome'), ('otros', 'Otro')], max_length=50),
        ),
        migrations.DeleteModel(
            name='IconoUsuario',
        ),
    ]
