# Generated by Django 5.2 on 2025-06-01 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iconos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, default='', max_length=50)),
                ('icono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconos.icono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('primer_apellido', models.CharField(default='Apellido', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=100)),
                ('cargo_profesional', models.CharField(default='Desarrollador Web', max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('habilidades', models.ManyToManyField(blank=True, to='headerProfesional.habilidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
