# Generated by Django 5.2 on 2025-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='header',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
    ]
