# Generated by Django 5.2 on 2025-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0002_header_email_header_github_header_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
