# Generated by Django 5.2 on 2025-06-09 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0003_header_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='habilidades',
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='header',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (mínimo 7 dígitos, con o sin +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
