# Generated by Django 5.2 on 2025-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0004_remove_header_habilidades_alter_habilidad_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='headerProfesional.habilidad'),
        ),
    ]
