# Generated by Django 5.2 on 2025-06-09 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0005_header_habilidades'),
        ('iconos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='habilidades',
        ),
        migrations.AddConstraint(
            model_name='habilidad',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_habilidad_por_usuario'),
        ),
    ]
