# Generated by Django 5.2 on 2025-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0006_remove_header_habilidades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveConstraint(
            model_name='habilidad',
            name='unique_habilidad_por_usuario',
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='', max_length=50),
        ),
    ]
