# Generated by Django 5.2 on 2025-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0007_alter_habilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='', max_length=50),
        ),
    ]
