# Generated by Django 5.2 on 2025-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0008_alter_habilidad_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={},
        ),
    ]
