# Generated by Django 5.2 on 2025-06-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0009_alter_habilidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['nombre']},
        ),
    ]
