# Generated by Django 5.2 on 2025-06-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0010_alter_habilidad_options'),
        ('iconos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={},
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconos.icono')),
            ],
        ),
    ]
