# Generated by Django 5.2 on 2025-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headerProfesional', '0011_alter_habilidad_options_alter_habilidad_nivel_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
