# Generated by Django 5.2 on 2025-06-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoprofesional',
            name='link',
            field=models.URLField(blank=True, help_text='Link opcional relacionado con el objetivo', max_length=300, null=True),
        ),
    ]
