# Generated by Django 5.2 on 2025-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0002_objetivoprofesional_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivoprofesional',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='objetivoprofesional',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Usa números pequeños para ordenar manualmente'),
        ),
        migrations.AlterField(
            model_name='objetivoprofesional',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
