# Generated by Django 5.1.5 on 2025-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0003_alter_objetivoprofesional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoprofesional',
            name='modo_presentacion',
            field=models.CharField(choices=[('parrafo', 'Párrafos'), ('lista', 'Lista desordenada')], default='parrafo', max_length=10),
        ),
    ]
